[package]
name = "pff"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
http = "0.2.8"
icmp = "0.3.0"
reqwest = { version = "0.11.11", features = ["blocking"] }